import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios';
import { useEffect, useState } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  var key = '5714346188686087';
  const [data, setData] = useState({});
  const [name, setName] = useState('');
  const [playerCard, setPlayerCard] = useState({});
  const [cardOption1, setCardOption1] = useState({});
  const [cardOption2, setCardOption2] = useState({});
  const [cardOption3, setCardOption3] = useState({});
  const [cardOption4, setCardOption4] = useState({});
  const [cardOption5, setCardOption5] = useState({});

  /* FUNCTION FOR CALLING SUPERHERO API DATA TO cardOptions */
  function setCharacter(setcardoption,characterID) {
      useEffect(() => {
      //axios.get('https://superheroapi.com/api/5714346188686087/search/iron%20man')
      axios.get(`https://superheroapi.com/api.php/${key}/${characterID}`)
      .then((response) => {
        console.log(response.data)
        setcardoption(response.data)
      }).catch(err => {
        console.log(err)
      });
    },[])
  }

  /* function for only selecting one SUPERHERO checkbox  */
  function onlySelect(id){
    for (let i = 1; i < 6; i++) {
      document.getElementById("check" + i).checked = false;
    }
    document.getElementById(id).checked = true;
  }
  

  /* CALLING THE FUNCTION TO GET THE SUPERHERO DATA */
  setCharacter(setCardOption1,1)
  setCharacter(setCardOption2,100)
  setCharacter(setCardOption3,200)
  setCharacter(setCardOption4,300)
  setCharacter(setCardOption5,400)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div> {cardOption1.name} <input id="check1" type="checkbox" onChange={(e)=> onlySelect(e.target.id)} /> </div>
      <div> {cardOption2.name} <input id="check2" type="checkbox" onChange={(e)=> onlySelect(e.target.id)} /> </div>
      <div> {cardOption3.name} <input id="check3" type="checkbox" onChange={(e)=> onlySelect(e.target.id)} /> </div>
      <div> {cardOption4.name} <input id="check4" type="checkbox" onChange={(e)=> onlySelect(e.target.id)} /> </div>
      <div> {cardOption5.name} <input id="check5" type="checkbox" onChange={(e)=> onlySelect(e.target.id)} /> </div>
      
      <script>
        
      </script>
      </main>
    </>
  )
}
