import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { use, useEffect, useState } from "react";
import Lottie from "lottie-react";
import LoadingAnimation from "../public/loading.json";
import useSound from 'use-sound';

const inter = Inter({ subsets: ["latin"] });

import Card from '../components/card';


export default function Home() {
  var key = "5714346188686087";
  const [data, setData] = useState({});
  const [name, setName] = useState("");
  const [playerCard, setPlayerCard] = useState({image:"n\a"});
  const [botCard, setBotCard] = useState({});
  const [cardOption1, setCardOption1] = useState({});
  const [cardOption2, setCardOption2] = useState({});
  const [cardOption3, setCardOption3] = useState({});
  const [cardOption4, setCardOption4] = useState({});
  const [cardOption5, setCardOption5] = useState({});
  const [cardPower, setCardPower] = useState(0);

  const [loading, setLoading] = useState(true);
  const [quote, setQuote] = useState("")

  //SHOWS SELECTED CARD
  const [showCard, setShowCard] = useState(false);


  const [toc] = useSound("/sounds/toc.mp3");



  /* FUNCTION FOR CALLING SUPERHERO API DATA TO cardOptions */
  function setCharacter(setcardoption, characterID) {
    useEffect(() => {
      //axios.get('https://superheroapi.com/api/5714346188686087/search/iron%20man')
      axios
        .get(`https://superheroapi.com/api.php/${key}/${characterID}`)
        .then((response) => {
          console.log(response.data);
          setcardoption(response.data);
        })
        .catch((err) => {
          console.log(err);
        });
    }, []);
  }

  function getQuote() {
    useEffect(() => {
    axios
      .get('https://www.affirmations.dev/')
      .then((response) => {
        console.log(response);
        setQuote(response)
      })
      .catch((err) => {
        console.log(err);
      });
  }, [])
}

//CALCULATES SELECTED CARDS TOTAL POWERSTAT
  function calculatePower(player){
    var power = 0;
    var stats = [];
    
    stats.push(player.powerstats.combat)
    stats.push(player.powerstats.durability)
    stats.push(player.powerstats.intelligence)
    stats.push(player.powerstats.power)
    stats.push(player.powerstats.speed)
    stats.push(player.powerstats.strength)

    stats.forEach((stat) => {
      const num = parseInt(stat)
      power += num
    })
    setCardPower(power)
  }

//LOADING ANIMATION TIME
useEffect(() => {
  setTimeout(() => {
    setLoading(false);
  }, 2000);
});

  /* function for only selecting one SUPERHERO checkbox  */
  function onlySelect(id, playerCard) {
    for (let i = 1; i < 6; i++) {
      document.getElementById("check" + i).checked = false;
    }
    document.getElementById(id).checked = true;
    setPlayerCard(playerCard);
    calculatePower(playerCard)
  }

  /* CALLING THE FUNCTION TO GET THE SUPERHERO DATA */
  setCharacter(setCardOption1, 1);
  setCharacter(setCardOption2, 100);
  setCharacter(setCardOption3, 200);
  setCharacter(setCardOption4, 300);
  setCharacter(setCardOption5, 400);
  setCharacter(setBotCard, Math.floor((Math.random() * 731) + 1));


  //LOADING PAGE
  if (loading) {
    return (
      <div className="loadingCont">
        <div className="quote">{quote}</div>
        <Lottie
        className="loader"
          style={{ width: 500, height: 500 }}
          animationData={LoadingAnimation}
          loop={true}
        />
        <img className="loadingSplash" src="../placeholder.jpg" />
      </div>
    );
  }

  //CARD SELECTION
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="optionsContainer">
          <div className="cardContainer">
            <img
              style={{ height: "35vh" }}
              src={cardOption1.image.url}
              alt=""
              srcSet=""
            />
            {cardOption1.name}{" "}
            <input
              id="check1"
              type="checkbox"
              onChange={(e) => onlySelect(e.target.id, cardOption1)}
              onClick={() => {
                 setShowCard(true)
                 {toc ("/sounds/toc.mp3")};
                 }}
              
            />
          </div>
          <div className="cardContainer">
            <img
              style={{ height: "35vh" }}
              src={cardOption2.image.url}
              alt=""
              srcSet=""
            />
            {cardOption2.name}{" "}
            <input
              id="check2"
              type="checkbox"
              onChange={(e) => onlySelect(e.target.id, cardOption2)}
              onClick={() => {
                 setShowCard(true)
                 {toc ("public/sounds/toc.mp3")};
                 }}
            />
          </div>
          <div className="cardContainer">
            <img
              style={{ height: "35vh" }}
              src={cardOption3.image.url}
              alt=""
              srcSet=""
            />
            {cardOption3.name}{" "}
            <input
              id="check3"
              type="checkbox"
              onChange={(e) => onlySelect(e.target.id, cardOption3)}
              onClick={() => {
                 setShowCard(true)
                 {toc ("public/sounds/toc.mp3")};
                 }}
            />
          </div>
          <div className="cardContainer">
            <img
              style={{ height: "35vh" }}
              src={cardOption4.image.url}
              alt=""
              srcSet=""
            />
            {cardOption4.name}{" "}
            <input
              id="check4"
              type="checkbox"
              onChange={(e) => onlySelect(e.target.id, cardOption4)}
              onClick={() => {
                 setShowCard(true)
                 {toc ("public/sounds/toc.mp3")};
                 }}
            />
          </div>
          <div className="cardContainer">
            <img
              style={{ height: "35vh" }}
              src={cardOption5.image.url}
              alt=""
              srcSet=""
            />
            {cardOption5.name}{" "}
            <input
              id="check5"
              type="checkbox"
              onChange={(e) => onlySelect(e.target.id, cardOption5)}
              onClick={() => {
                 setShowCard(true)
                 {toc ("public/sounds/toc.mp3")};
                 }}
            />
          </div>
        </div>
        


      {   
        showCard ?     
        <Card name={playerCard.name} src={playerCard.image.url} power={cardPower}/>
        : null
      } 

        <div> Your Superhero: {playerCard.name} </div>
        <div className="cardContainer">
            <img
              style={{ height: "35vh" }}
              src={botCard.image.url}
              alt=""
              srcSet=""
            />
            {botCard.name}{" "}
          </div>
        <div> You will be fighting against: {botCard.name}</div>
      </main> 
    </>
  );
}
